# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengrace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCommentTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name=b'created')),
                ('name', models.TextField(default=b'')),
                ('text', models.TextField()),
                ('keyword', models.TextField()),
            ],
        ),
    ]
